# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d79d4b880149dfd12e2f75ece6fd55acb048b09177b725666484a0f47c3ef21f5804ba1a9e16662e931e6728339d2a0f8221e592c1f1e54db70c99814e561c94

test:
  secret_key_base: 3f4a1749f350e535e6312fe4c30d2e142cd3a586ae82357e9c31d334a8028ae21334fbbeeb29eb3eafd9b16ad80b41bef8915908e58efae312ce6449fe90cca1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
